TestWeb/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^angular/', include('angular_app.urls', namespace='angular_app')),
    url(r'^d3/', include('d3_app.urls', namespace='d3_app')),
]

angular_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^team_list/$', views.team_list, name='team_list'),
    url(r'^file_upload/$', views.file_upload, name='file_upload'),
    url(r'^socket_io/$', views.socket_io, name='socket_io'),
]

d3_app/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

angular_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

d3_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

angular/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'angular/index.html')

angular_app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'angular_app/index.html')


def team_list(request):
    return render(request, 'angular_app/team_list.html')


def file_upload(request):
    return render(request, 'angular_app/file_upload.html')


def socket_io(request):
    return render(request, 'angular_app/socket_io.html')

d3_app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'd3_app/index.html')

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

angular/templates/angular/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link href="{% static 'angular/test_app.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="TestApp" ng-controller="TestCtrl">
{#        <h3>{$ title $}</h3>#}
{#        <div hello>Bob</div>#}
{#        <expander class="expander" expander-title="title">#}
{#            {$ text $}#}
{#        </expander>#}
        <accordion>
            <expander class="expander" ng-repeat="expander in expanders" expander-title="expander.title">
                {$ expander.text $}
            </expander>
        </accordion>

    </div>

{% endblock content %}


{% block custom_js %}
    <script src="{% static 'angular/test_app.js' %}"></script>
{% endblock custom_js %}

angular_app/templates/angular_app/file_upload.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link href="{% static 'jquery-ui/themes/base/jquery-ui.min.css' %}" rel="stylesheet">
{#    <link href="{% static 'angular_app/file_upload.css' %}" rel="stylesheet">#}
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="myApp" ng-controller="MainCtrl">
        File Upload:
        <input id="testUpload"
               type="file"
               fileupload
               name="files[]"
               data-url=/server/uploadFile"
               multiple
               done="uploadFinished(e, data)">

    </div>

{% endblock content %}


{% block custom_js %}
    <script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'blueimp-file-upload/js/vendor/jquery.ui.widget.js' %}"></script>
    <script src="{% static 'blueimp-file-upload/js/jquery.iframe-transport.js' %}"></script>
    <script src="{% static 'blueimp-file-upload/js/jquery.fileupload.js' %}"></script>
    <script src="{% static 'angular_app/myapp_directives.js' %}"></script>
    <script src="{% static 'angular_app/file_upload.js' %}"></script>
{% endblock custom_js %}

angular_app/templates/angular_app/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link href="{% static 'jquery-ui/themes/base/jquery-ui.min.css' %}" rel="stylesheet">
    <link href="{% static 'angular_app/test_app.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="TestApp" ng-controller="TestCtrl">
{#        <h3>{$ title $}</h3>#}
{#        <div hello>Bob</div>#}
{#        <expander class="expander" expander-title="title">#}
{#            {$ text $}#}
{#        </expander>#}
        <accordion>
            <expander class="expander" ng-repeat="expander in expanders" expander-title="expander.title">
                {$ expander.text $}
            </expander>
        </accordion>

        <div ng-controller="MainCtrl">
            <input id="dateField" datepicker ng-model="currentDate" select="updateMyText(date)">
            <br/>
            {$ myText $} - {$ currentDate $}
        </div>

        <div ng-controller="ParentCtrl">

            <div ng-controller="SelfCtrl">

                <a class="btn" ng-click="click()">click me</a>
                <div ng-controller="ChildCtrl"></div>

            </div>

            <div ng-controller="BroCtrl"></div>
        </div>

    </div>

{% endblock content %}


{% block custom_js %}
    <script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'angular_app/test_app.js' %}"></script>
{% endblock custom_js %}

angular_app/templates/angular_app/paginator.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
{#    <link href="{% static 'jquery-ui/themes/base/jquery-ui.min.css' %}" rel="stylesheet">#}
{#    <link href="{% static 'angular_app/test_app.css' %}" rel="stylesheet">#}
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="myApp" ng-controller="MainCtrl">
        <input type="text" ng-model="query">
        <ul>
            <li ng-repeat="item in searchPaginator.currentPageItems">
                {$ item $}
            </li>
        </ul>
    <a href=""
       ng-click="searchPaginator.previous()"
       ng-show="searchPaginator.hasPrevious()">&lt;&lt; Prev</a>
    <a href=""
       ng-click="searchPaginator.next()"
       ng-show="searchPaginator.hasNext()">Next &gt;&gt;</a>

    </div>

{% endblock content %}


{% block custom_js %}
{#    <script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>#}
    <script src="{% static 'angular_app/paginator_service.js' %}"></script>
    <script src="{% static 'angular_app/paginator.js' %}"></script>
{% endblock custom_js %}

angular_app/templates/angular_app/socket_io.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
{#    <link href="{% static 'jquery-ui/themes/base/jquery-ui.min.css' %}" rel="stylesheet">#}
{#    <link href="{% static 'angular_app/test_app.css' %}" rel="stylesheet">#}
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="myApp" ng-controller="MainCtrl">
        <input type="text" ng-model="message">
        <button ng-click="broadcast()">Broadcast</button>
        <ul>
            <li ng-repeat="msg in messages">{$ msg $}</li>
        </ul>
    </div>

{% endblock content %}


{% block custom_js %}
{#    <script src="{% static 'jquery-ui/jquery-ui.min.js' %}"></script>#}
    <script src="{% static 'socket.io-client/socket.io.js' %}"></script>
    <script src="{% static 'angular_app/socket_io.js' %}"></script>
{% endblock custom_js %}

angular_app/templates/angular_app/team_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
{#    <link href="{% static 'angular_app/team_list.css' %}" rel="stylesheet">#}
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="myApp">
        <div class="row col-md-12" ng-controller="FilterCtrl">
            <form class="form-horizontal">
                <div class="form-group">
                    <label class="col-md-2" for="searchTextBox">Search:</label>
                    <div class="col-md-4">
                        <input class="form-control" type="text" id="searchTextBox" ng-model="filterService.searchText">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2" for="sportComboBox" class="control-label">Sport:</label>
                    <div class="col-md-4">
                        <select class="form-control" id="sportComboBox" ng-model="filterService.activeFilters.sport">
                            <option ng-repeat="sport in ['Basketball', 'Hockey', 'Football']">{$ sport $}</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2" for="cityComboBox" class="control-label">City:</label>
                    <div class="col-md-4">
                        <select class="form-control" id="cityComboBox" ng-model="filterService.activeFilters.city">
                            <option ng-repeat="city in ['Dallas', 'Los Angeles', 'Boston', 'New York']">{$ city $}</option>
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2" class="control-label">Featured:</label>
                    <div class="col-md-4">
                        <input type="checkbox" ng-model="filterService.activeFilters.featured" ng-false-value=""/>
                    </div>
                </div>
            </form>
        </div>
        <div class="row col-md-12" ng-controller="ListCtrl">
            <table class="table">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Sport</th>
                    <th>City</th>
                    <th>Featured</th>
                </tr>
                </thead>
                <tbody id="teamListTable">
                <tr ng-repeat="team in teamsList | filter:filterService.activeFilters | filter:filterService.searchText">
                    <td>{$ team.name $}</td>
                    <td>{$ team.sport $}</td>
                    <td>{$ team.city $}</td>
                    <td>{$ team.featured $}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>


{% endblock content %}


{% block custom_js %}
    <script src="{% static 'angular_app/myapp_services.js' %}"></script>
    <script src="{% static 'angular_app/team_list.js' %}"></script>
{% endblock custom_js %}

d3_app/templates/d3_app/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link href="{% static 'd3_app/index.css' %}" rel="stylesheet">

{% endblock custom_css %}

{% block content %}
    <div class="container-fluid" ng-app="myApp" ng-controller="MainCtrl">
    <div class="row">
        <div class="col-md-offset-1 col-md-10" id='main_chart'>
            <svg id="chart"></svg>
        </div>
    </div>

    </div>

{% endblock content %}


{% block custom_js %}
    <script src="{% static 'd3/d3.min.js' %}"></script>
    <script src="{% static 'd3-plugins/sankey/sankey.js' %}"></script>
    <script src="{% static 'd3_app/index.js' %}"></script>

{% endblock custom_js %}

main/templates/main/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link href="{% static 'main/test_app.css' %}" rel="stylesheet">
{% endblock custom_css %}

{% block content %}
    <div class="container" ng-app="TestApp" ng-controller="TestCtrl">
{#        <h3>{$ title $}</h3>#}
{#        <div hello>Bob</div>#}
{#        <expander class="expander" expander-title="title">#}
{#            {$ text $}#}
{#        </expander>#}
        <accordion>
            <expander class="expander" ng-repeat="expander in expanders" expander-title="expander.title">
                {$ expander.text $}
            </expander>
        </accordion>

    </div>

{% endblock content %}


{% block custom_js %}
    <script src="{% static 'main/test_app.js' %}"></script>
{% endblock custom_js %}

templates/base.html
<!DOCTYPE html>

{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TestWeb</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">

    {% block custom_css %}{% endblock custom_css %}
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">TestWeb</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'angular_app:index' %}">Angular</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div>
</nav>

<div class="container-fluid">
    {% block content %}{% endblock content %}
</div>

<!-- jquery -->
<script src="{% static 'jquery/dist/jquery.min.js' %}"></script>

<!-- bootstrap -->
<script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
<!-- angular -->
<script src="{% static 'angular/angular.min.js' %}"></script>
{#<script src="{% static 'angular-resource/angular-resource.min.js' %}"></script>#}
{#<script src="{% static 'checklist-model/checklist-model.js' %}"></script>#}
<!--<script src="{% static 'angular-datatables/dist/angular-datatables.min.js' %}"></script>-->
<!--<script src="{% static 'angular-datatables/dist/plugins/bootstrap/angular-datatables.bootstrap.min.js' %}"></script>-->
<!--<script src="{% static 'angular-bootstrap/ui-bootstrap.min.js' %}"></script>-->
<!--<script src="{% static 'angular-bootstrap/ui-bootstrap-tpls.min.js' %}"></script>-->

{% block custom_js %}{% endblock custom_js %}

</body>
</html>